Rails.application.config.assets.precompile += %w( users.css )
Rails.application.config.assets.precompile += %w( users.js )
Rails.application.config.assets.precompile += %w( cemeteries.css )
Rails.application.config.assets.precompile += %w( cemeteries.js )
Rails.application.config.assets.precompile += %w( plots.css )
Rails.application.config.assets.precompile += %w( plots.js )
Rails.application.config.assets.precompile += %w( welcome.css )
Rails.application.config.assets.precompile += %w( welcome.js )