development: 
   adapter: mysql2
   encoding: utf8 
   database: example 
   pool: 10 
   username: root 
   password: <%= ENV["DB_DEV_PASSWORD"] %>
   socket: /var/run/mysqld/mysqld.sock 
   reconnect: true

production: 
   adapter: mysql2
   encoding: utf8 
   database: example 
   pool: 10 
   username: root 
   password: <%= ENV["DB_PRODUCTION_PASSWORD"] %>
   socket: /var/run/mysqld/mysqld.sock 
   reconnect: true